version: '3'

services:
  gridlabd:
    build:
      context: .

  mysql:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: foo
      MYSQL_DATABASE: foo
