name: Container Build
on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GHCR
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: builder image
        uses: docker/build-push-action@v2
        with:
          context: .
          cache-from: |
            type=gha,scope=builder
            type=gha,scope=runner
          cache-to: |
            type=gha,scope=builder
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:builder
          target: builder

      - name: runner image
        uses: docker/build-push-action@v2
        with:
          cache-from: |
            type=gha,scope=builder
            type=gha,scope=runner
          cache-to: |
            type=gha,scope=runner
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          target: runner
